# Configuration for pocketdvdnet
batch_size: 64    
patch_size: 160
test_batch_size: 1000  
epochs: 14    
lr: 0.002
gamma: 0.1
noise_ival: [5, 55]
val_noiseL: 25.0

no_accel: false      
dry_run: false      

seed: 1        

out_dir: "/user/home/xs23823/work/studfastdvdnet/out_mse"
valset_dir:  "/user/home/xs23823/work/studfastdvdnet/DAVIS 420p JPEG VAL"
trainset_dir: "/user/home/xs23823/work/PaCNet-denoiser/train"
iterations: 40000   
num_workers: 6
num_prefetch_queue: 16
log_freq: 10

scheduler:
  name: "StepLR"
  step_size: 30
  gamma: 0.5

use_obproxsg: false
reset_lr: false #reset the learning rate when resuming training
use_distillation: false        
loss_type: "mse"  

