# configs/net.yaml

# Configuration for PyTorch MNIST Example

batch_size:      64   
test_batch_size: 1000 
epochs:          14   
lr:              1.0  
gamma:           0.7  

no_accel:   false     
dry_run:    false     
save_freq:  1

seed:         1       
log_interval: 10      

out_dir: "./out"
iterations: 20000
num_workers: 8
num_prefetch_queue: 8
log_freq: 10

scheduler:
  name: "StepLR"
  step_size: 1
  gamma: 0.7
