# configs/fastdvdnet.yaml

# Configuration for pruning FastDVDNet
batch_size: 64    
patch_size: 96
test_batch_size: 1000  
epochs: 14    
lr: 0.000015
gamma: 0.1
noise_ival: [5, 55]
val_noiseL: 25.0

no_accel: false      
dry_run: false      

seed: 1        

out_dir: "/home/imogend/Documents/Data/out_extra_data"
valset_dir: "/home/imogend/Documents/Data/DAVIS 420p JPEG VAL"
trainset_dir: "/home/imogend/Documents/Data/PNG_TRAINING_SEQUENCES"
iterations: 270000
num_workers: 12
num_prefetch_queue: 16
log_freq: 10

scheduler:
  name: "StepLR" 
  step_size: 10000
  gamma: 0.8

# pruning additions
use_obproxsg: true
lambda_reg: 0.09
epochSize: 10
Np: 2
"No": "inf" # - careful as yaml interprets No as a bool lol 
eps: 0.001
weight_decay: 0
reset_lr: true
lambda_warmup_steps: 1 
sparsity_threshold: 33.4 #highest sparsity will be saved as long as the psnr is above this value